### ISSUE TITLE
not sure what is wrong

### ISSUE THREAD

**Issue by AnshhSingh** [WocketSesh/example-revolt-bot#1]
trying to run this file but getting some errors and i have no idea what is wrong 

![image](https://user-images.githubusercontent.com/28798608/132989900-92f5517a-1684-4b5d-9013-c25bd8c3a5fc.png)
this happens whenever i try to run a command
using node 14.17.0

**Comment by WocketSesh** [comment]
the issue you're having is message.member.roles is returning null.
![image](https://user-images.githubusercontent.com/75913734/133041642-057efd65-9fe0-45d2-85f2-636a7b8a9f76.png)
for now you can just go to here in revolt-handler/main.js, and add a check to see whether message.member.roles is null or not, the reason it is returning null i have no idea, i'll look into it later

i also can't reproduce this issue are you sure you're the most recent version of revolt.js, and i haven't tested this at all with a user account, so if you're using  a user account rather than a bot that may be the issue

**Comment by AnshhSingh** [comment]
thanks for the reply, could you please state the exact nodejs version you are using? i am using a bot account btw

**Comment by WocketSesh** [comment]
> thanks for the reply, could you please state the exact nodejs version you are using? i am using a bot account btw

I tested with node v14.17.5 and it worked fine

**Comment by AnshhSingh** [comment]
> > thanks for the reply, could you please state the exact nodejs version you are using? i am using a bot account btw
> 
> I tested with node v14.17.5 and it worked fine

thanks
